version: '3.9'

services:
    app:
        container_name: go-sso-app
        build:
            context: .
            dockerfile: dev.Dockerfile
        env_file: .env
        ports:
            - ${GRPC_PORT}:${GRPC_PORT}
        environment:
            - CONFIG_PATH=${CONFIG_PATH}
        depends_on:
            - postgres
        volumes:
            - .:/app

    postgres:
        image: postgres:15
        container_name: go-sso-db
        restart: always
        ports:
            - "${POSTGRES_OUT_PORT}:5432"
        env_file:
            -   .env
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_OUT_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

    migrate:
        image: migrate/migrate
        container_name: go-sso-migrate
        entrypoint: [
            "sh", "-c",
            "sleep 5 && migrate -path /migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable up"
        ]
        depends_on:
            - postgres
        volumes:
            - ./migrations:/migrations

volumes:
    pgdata: