version: "3"

tasks:
    local-up:
        desc: Запуск локального сервера в режиме разработки c live reload
        cmds:
            - |
                docker-compose \
                   --env-file docker/.env.local \
                  -f docker/docker-compose.local.yml \
                  -p go-sso \
                  up -d --build
    func-test:
        desc: Запуск функциональных тестов в директории tests
        cmds:
            - go test -v ./tests/...
        env:
            GO111MODULE: on
    unit-test:
        desc: Запуск юнит-тестов в директории internal
        cmds:
            - go test -v ./internal/...
        env:
            GO111MODULE: on
