version: "3"

tasks:
    func-test:
        desc: Запуск функциональных тестов в директории tests
        cmds:
            - go test -v ./tests/...
        env:
            GO111MODULE: on
    unit-test:
        desc: Запуск юнит-тестов в директории internal
        cmds:
            - go test -v ./internal/...
        env:
            GO111MODULE: on
