CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
	uuid UUID PRIMARY KEY DEFAULT uuid_generate_v4 (),
	email TEXT NOT NULL UNIQUE,
	pass_hash BYTEA NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_email ON users (email);

CREATE TABLE IF NOT EXISTS apps (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	secret TEXT NOT NULL UNIQUE
);
