version: "3.9"

services:
    app:
        container_name: go-sso-app_dev
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
        env_file: .env.dev
        networks:
            - shared-net
        volumes:
            - ${CONFIG_DIR}/:/app/config
        ports:
            - ${GRPC_PORT}:${GRPC_PORT}
        environment:
            - CONFIG_PATH=${CONFIG_PATH}
        depends_on:
            - postgres

    postgres:
        container_name: go-sso-db_dev
        image: postgres:15
        restart: always
        ports:
            - "${POSTGRES_OUT_PORT}:5432"
        env_file:
            - .env.dev
        networks:
            - shared-net
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: 5432
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    migrate:
        container_name: go-sso-migrate_dev
        image: migrate/migrate
        networks:
            - shared-net
        depends_on:
            - postgres
        volumes:
            - ../migrations:/migrations
        entrypoint:
            [
                "sh",
                "-c",
                "sleep 5 && migrate -path /migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@go-sso-db_dev:5432/${POSTGRES_DB}?sslmode=disable up",
            ]

    vault:
        container_name: go-sso-vault_dev
        image: hashicorp/vault:1.15
        restart: unless-stopped
        cap_add:
            - IPC_LOCK
        env_file: .env.dev
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: root
            VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        ports:
            - "${VAULT_OUT_PORT}:8200"
        networks:
            - shared-net
        command: server -dev

networks:
    shared-net:
        # external: true
