version: "3.9"

services:
    app:
        build:
            context: ../
            dockerfile: ./docker/local.Dockerfile
        env_file: .env.local
        networks:
            - shared-net
        ports:
            - ${GRPC_PORT}:${GRPC_PORT}
        environment:
            - CONFIG_PATH=${CONFIG_PATH}
        depends_on:
            - postgres
        volumes:
            # - ../config/:/app/config
            - ../:/app

    postgres:
        image: postgres:15
        restart: always
        ports:
            - "${POSTGRES_OUT_PORT}:5432"
        env_file: .env.local
        networks:
            - shared-net
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_PORT: ${POSTGRES_OUT_PORT}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data

    migrate:
        image: migrate/migrate
        networks:
            - shared-net
        entrypoint:
            [
                "sh",
                "-c",
                "sleep 5 && migrate -path /migrations -database postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@go-sso-db:5432/${POSTGRES_DB}?sslmode=disable up",
            ]
        depends_on:
            - postgres
        volumes:
            - ./migrations:/migrations

    vault:
        image: hashicorp/vault:1.15
        restart: unless-stopped
        cap_add:
            - IPC_LOCK
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: root
            VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
        ports:
            - "8200:8200"
        networks:
            - shared-net
        command: server -dev

volumes:
    pgdata:

networks:
    shared-net:
        external: true
