env: "local" # dev, prod
token_ttl: 1h
grpc:
    port: 50055
    timeout: 10h
    host: localhost

psql:
    host: postgres
    port: 5432

    user: sso
    password: postgres
    db: go-sso

vault:
    addr: ${VAULT_ADDR}
    token: ${VAULT_TOKEN}
