env: "prod"
token_ttl: 20m
grpc:
    port: 50055
    timeout: 30s
    host: localhost

psql:
    host: 147.45.72.209
    port: 5433
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    db: ${POSTGRES_DB}

    migrator:
        path: "./migrations"

vault:
    addr: ${VAULT_ADDR}
    token: ${VAULT_TOKEN}
    timeout: 20s
