env: "local" # dev, prod
token_ttl: 1h
grpc:
    host: localhost
    port: 50055
    timeout: 10h

psql:
    host: localhost
    port: 5434

    user: sso
    pass: postgres
    db: go-sso

    # база данных для тестов
    migrator:
    path: "./tests/migrations"
    table: "migrations_test"

vault:
    addr: ${VAULT_ADDR}
    token: ${VAULT_TOKEN}
    timeout: 20s
