env: "dev"
token_ttl: 100h
grpc:
    host: localhost
    port: 50055
    timeout: 10h

psql:
    host: localhost
    port: 5434
    user: sso
    password: postgres
    db: go-sso

    # база данных для тестов
    migrator:
        path: "./tests/migrations"
        table: "migrations_test"

vault:
    addr: http://go-sso-vault:8200
    token: root
    timeout: 20s
