name: CI

on:
    push:
        branches:
            - master
            - develop
        tags:
            - "v*.*.*"
    pull_request:
        branches:
            - master
            - develop
        tags:
            - "v*.*.*"

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.24.1"

            - name: Update PATH
              run: echo "${{ runner.workspace }}/bin" >> $GITHUB_PATH

            - name: Install Task
              run: |
                  curl -sSL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin

            - name: Install dependencies
              run: |
                  go mod download

            - name: Run tests
              run: task unit-test

    integration-test:
        runs-on: ubuntu-latest

        services:
            docker:
                image: docker:20.10.16
                options: --privileged

        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: "1.24.1"

            - name: Update PATH
              run: echo "${{ runner.workspace }}/bin" >> $GITHUB_PATH

            - name: Install Task
              run: |
                  curl -sSL https://taskfile.dev/install.sh | sh -s -- -d -b /usr/local/bin

            - name: Install dependencies
              run: |
                  go mod download

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Set up Docker Compose
              run: |
                  sudo apt-get update
                  sudo apt-get install docker-compose -y

            - name: Build and start services
              run: |
                  export CONFIG_DIR=./config/dev.yml
                  docker compose \
                        --env-file docker/.env.dev \
                        -f docker/docker-compose.dev.yml \
                        up -d

            - name: Run integration tests
              run: |
                  sleep 5
                  export CONFIG_PATH=/app/config/dev.yml
                  task func-test
