name: CI/CD

# Необходимые переменные на github:
# vars.DOCKERHUB_USERNAME - логин в dockerhub
# secrets.DOCKERHUB_TOKEN - токен доступа к dockerhub

on:
    push:
        tags:
            - "v*.*.*" # любые теги вида v1.0.0

jobs:
    build:
        environment: production

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set version
              uses: ./.github/actions/set-version

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ vars.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  no-cache: true
                  file: ./prod.Dockerfile
                  platforms: linux/amd64, linux/arm64
                  tags: |
                      ${{ github.repository }}:latest
                      ${{ github.repository }}:${{ env.VERSION }}
